### ISSUE TITLE
Can't open Package.swift in Xcode 14.*

### ISSUE THREAD

**Issue by icanzilb** [simonbs/Runestone#122]
**Describe the bug**
Downloading the repo from GitHub and double clicking on Package.swift fails to build.

**To Reproduce**
Download the repo from GitHub, double click Package.swift.

**Expected behavior**
Builds.

**Screenshots**

<img width="433" alt="image" src="https://user-images.githubusercontent.com/633862/179461176-31f9705a-e84e-42dc-be2d-9fca9b161568.png">

I get a similar error when trying to open the Example project:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/633862/179461322-bd39dbc9-769b-41e7-aaa2-f091b234a165.png">

**Additional context**
I checked Getting Started but I didn't see any additional steps spelled out. I'm not sure what I'm doing wrong

**Comment by shaps80** [comment]
FYI: I'm experiencing the same issue 👍

**Comment by simonbs** [comment]
That seems to be because tree-sitter is added as a submodule. GitHub doesn't download those when downloading a repository. I'm not sure if there's a way I can work around this.

Runestone builds when cloning it along the submodule using:

```sh
git clone --recursive git@github.com:simonbs/Runestone.git
```

**Comment by simonbs** [comment]
> Perhaps that needs to go in the README somewhere, or Contribute guide?

That's a good idea! I've added it in #126.

**Comment by simonbs** [comment]
Closing this as it seems resolved by the additional details in the README. Don't hesitate to reopen the issue if that isn't the case though.
