### ISSUE TITLE
API: support search in scopes

### ISSUE THREAD

**Issue by rebornix** [simonbs/Runestone#135]
**Describe the solution you'd like**

Supporting `range: NSRange` in the Search API like snippets below

```diff
public struct SearchQuery: Hashable, Equatable {
+    /// The range to search in
+    public let range: NSRange?

-    public init(text: String, matchMethod: MatchMethod = .contains, isCaseSensitive: Bool = false) {
+    public init(text: String, matchMethod: MatchMethod = .contains, isCaseSensitive: Bool = false, range: NSRange? = nil) {

    func matches(in string: NSString) -> [NSTextCheckingResult] {
        do {
            let regex = try NSRegularExpression(pattern: annotatedText, options: regularExpressionOptions)
-            return regex.matches(in: string as String, range: NSRange(location: 0, length: string.length)) 
+            return regex.matches(in: string as String, range: range ?? NSRange(location: 0, length: string.length))
        } catch {
            #if DEBUG
            print(error)
            #endif
            return []
        }
    }
```

Supporting search in specified ranges would allow embedders to control where the search should happen, making it possible to build features like

* Search in current block
* Search in Strings/Comments

**Describe alternatives you've considered**

We could search in all text and then do the filtering afterwards but that would be less performant.

I can send PRs if this makes sense to you.

**Comment by simonbs** [comment]
This sounds like a great addition. I'll be happy to merge a PR that introduces this functionality.
