### ISSUE TITLE
Cursor doesn't update position when changing text programmatically

### ISSUE THREAD

**Issue by zachwaugh** [simonbs/Runestone#141]
**Describe the bug**
When updating the text directly, the cursor position doesn't update until the next keystroke. I tested on 0.2.0 and on main.

**To Reproduce**
1. Type some text
2. Have a button that calls `textView.text = ""` or `textView.text = "any string"`, doesn't matter what you change it to as long as it's a different size from the original text
3. See that the cursor doesn't move from its previous position
4. Type another character and then the cursor will correct itself

**Expected behavior**
- Changing the text programmatically should always ensure the cursor and any other UI are updated as well

**Screenshots**
![runestone-bug](https://user-images.githubusercontent.com/21447/184359012-d4f90605-6384-4ba3-96b5-c3f147caa75c.gif)

**Additional context**
My use case here is I have a smaller input field and I want to provide a button to let the user to easily clear it all instead of having to select all and delete.

Note: I also tried using `textView.setState()` instead of `textView.text = ` in case I was using the wrong API. That resulted in the same UI bug, but additionally caused a crash on typing the next character:

<img width="1399" alt="Screen Shot 2022-08-12 at 9 01 30 AM" src="https://user-images.githubusercontent.com/21447/184359289-236070c2-1e41-42c8-ac06-9509a059993c.png">

I can file that crash separately, but I figured  fixing the underlying issue here would probably resolve the crash as well.

**Comment by simonbs** [comment]
@zachwaugh Thanks for your detailed bug report. The issue should be fixed in #143.
