### ISSUE TITLE
Can't move caret when in marked range

### ISSUE THREAD

**Issue by douknow** [simonbs/Runestone#142]
**Describe the bug**
When I use Runestone input Chinese, I press a char and marked range appear, then I change selectedRnage position by tap, bug when I continue input, the caret back to before change.

**To Reproduce**
Input Chinese.

**Expected behavior**
Like UITextView, can change selected range when in marked range

**Screenshots**
![image](https://user-images.githubusercontent.com/18661488/184496025-c8b6ae4c-2eaa-41b4-9abb-f1a7c759afd7.png)

**Additional context**

**Comment by simonbs** [comment]
@douknow Thanks for creating the bug report. This issue should be fixed by #145.

**Comment by douknow** [comment]
Thank you for your amazing work🥳
