### ISSUE TITLE
[Feature Request] Open Files from iCloud Drive HIDDEN Folders

### ISSUE THREAD

**Issue by FelipeRearden** [simonbs/Runestone#15]
Hello @simonbs !!!!

My FR for the amazing Runestone is simple to explain: be able to open files (.css in my case) that are located inside iCloud Drive **but in a hidden folder**

💡 Let me explain why this is so important to me :)

## My Workflow

I use [Obsidian](https://obsidian.md/) as my texto editor for `.md` files on iPadOS using a keyboard and a mouse.

Based on the way that Obsidian was developed, all the internal content of Obsidian is inside a hidden folder that is located inside a Folder in iCloud Drive 

On iCloud we have this structure:

iCloudDrive >> Obsidian Folder >> Main Folder >> .obsidian (hidden folder) >> snippets (hidden folder)

![C6061175-3363-417B-A679-DDD3162D3DCF](https://user-images.githubusercontent.com/85180696/166937170-0afe7d80-b17e-47ac-8c4f-0c2cd0e23a4f.jpeg)

The `.obsidian/snippets` folder has the `.css` files that re used by users to customize the Obsidian UI
- I want to use **Runestone** to edit my `.css` files that are placed in a hidden folder.

✅ This is the reason that i’m asking for this feature  🙏 

---

I’m aware that the App Textastic already have this Feature. 

BUT I really love Runestone and I want to use it more in my daily workflow. 

Moreover,  I want to support your work because I use all your apps and I really like to the attention to details that you have with your apps 💙 

--- 

Thanks for reading this !

I wish you a fantastic  launch day 🚀

**Comment by simonbs** [comment]
@FelipeRearden Thanks for your feature request. However, this request seem to be related to the [Runestone app](https://apps.apple.com/us/app/runestone-editor/id1548193893) where as this issue tracker is concerned with the Runestone framework. I get it, it's confusing that the two have the same name 😊

The Runestone app uses Apple's default file browser which, unfortunately, doesn't support showing hidden files and folders. Whenever they add support for that (🤞) I'll happily support it in Runestone too.

I'm closing the PR as it isn't relevant to the project hosted in this repository but know that your feedback have been noted.

**Comment by FelipeRearden** [comment]
> @FelipeRearden Thanks for your feature request. However, this request seem to be related to the [Runestone app](https://apps.apple.com/us/app/runestone-editor/id1548193893) where as this issue tracker is concerned with the Runestone framework. I get it, it's confusing that the two have the same name 😊

First of all, forgive for my lack of knowledge :)

I was so excited about Runestone that I tried everything that I could to share with you this FR. 

Thanks for understanding 😅

> The Runestone app uses Apple's default file browser which, unfortunately, doesn't support showing hidden files and folders. Whenever they add support for that (🤞) I'll happily support it in Runestone too.

100% understood 👍

I really appreciate this feature when is possible in the future. 

I'm trying to use Shortcuts to access/edit/add files in the hidden folders using Toolbox Pro but unfortunately is not going well.

> I'm closing the PR as it isn't relevant to the project hosted in this repository but know that your feedback have been noted.

Sure!

Thank you very much for your kind words and forgive again for my mistake. 

I wish you a fantastic day and thank you very much for bring this amazing apps to us. 

Your work bring joy to our lives everyday ✨
