### ISSUE TITLE
`textViewDidChangeSelection(_:)` called twice when deleting a character

### ISSUE THREAD

**Issue by nighthawk** [simonbs/Runestone#158]
**Describe the bug**
Tiny difference compared to UITextView: When deleting a character using backspace the delegate's `textViewDidChangeSelection(_:)` is called twice: once with `length = 1` of the character to be deleted and then again with `length =  0` of the actual selection.

**To Reproduce**
Implement `TextViewDelegate`, in particular the `textViewDidChangeSelection(_:)` method. Print `textView.selectedRange` in there. Then delete a character.

**Expected behavior**
Only called once with `length = 0`.

**Additional context**
UITextView only calls it once with `length = 0`.

It caused funny behaviour in my app, but I can work around this on my end by using a debounce of that signal. Might be worth fixing to align with UITextView's behaviour.

I only tested this in a Mac Catalyst app.

Stacktrace of call with `length = 1`:

```
#2	0x000000010de2ab84 in TextView.textInputViewDidChangeSelection(_:) at .../Runestone/Sources/Runestone/TextView/TextView.swift:1301
#3	0x000000010de2bf68 in protocol witness for TextInputViewDelegate.textInputViewDidChangeSelection(_:) in conformance TextView ()
#4	0x000000010ddf577c in TextInputView.selectedTextRange.setter at .../Runestone/Sources/Runestone/TextView/TextInput/TextInputView.swift:40
#5	0x000000010ddf53f8 in @objc TextInputView.selectedTextRange.setter ()
#6	0x00000001b1607238 in -[UIKBInputDelegateManager _deleteBackwardAndNotify:] ()
#7	0x0000000209779498 in -[UIKeyboardImplAccessibility deleteBackwardAndNotify:] ()
#8	0x00000001b189fb60 in -[UIKeyboardImpl performTextOperationActionSelector:] ()
```

**Comment by simonbs** [comment]
@nighthawk Thanks for reporting this bug. It should be fixed in #167.
