### ISSUE TITLE
Add some popular tab representations

### ISSUE THREAD

**Issue by muescha** [simonbs/Runestone#171]
**Is your feature request related to a problem? Please describe.**

i like to use a different tab symbols. i don't need the triangle - but the common one.
i google for `unicode tab symbol` but don't find a good one ad hoc.

**Describe the solution you'd like**

add some default ones somehow like this
```swift
textView.tabSymbol = .triagle       // ▸
textView.tabSymbol = .arrow	        // ➝
textView.tabSymbol = .arrowBar      // ⇥
```

**Describe alternatives you've considered**

or add this symbols to the docs for copy paste ;)

**Additional context**

**Comment by simonbs** [comment]
Adding the common symbols is a great idea. I've added it to the documentation in #174.
