### ISSUE TITLE
Question Regarding KeyboardToolsView Example

### ISSUE THREAD

**Issue by garikmi** [simonbs/Runestone#209]
In the example, you have to pass `TextView` into `KeyboardToolsView(textView:)` and then assign it to the same `TextView.inputAccessoryView`. Doesn't that create a retain cycle (at least that's what I get)? I wasn't able to run the Example on my machine (I will try again). Just wanna know if I am doing something wrong within my implementation.

**Comment by simonbs** [comment]
The KeyboardToolsView only holds a weak reference to the instance of TextView, and as such, there is no retain cycle.

Had the KeyboardToolsView held a strong reference to the instance TextView, then there would indeed have been a retain cycle.

Closing this issue as I suppose your question has been answered. Don't hesitate to reopen the issue if that is not the case.
