### ISSUE TITLE
Insert current timestamp

### ISSUE THREAD

**Issue by amay5267** [simonbs/Runestone#219]
Hi @simonbs 

how can i insert current date timestamp?
Can you provide button for that as well?
Automating timestamp like this would be nice :
Thu Oct 13 23:23:00 GMT 2022

**Comment by simonbs** [comment]
Thanks for your feature request. Runestone does not provide a shortcut to insert the current timestamp.

I'll close this issue since it seems more related to the Runestone Text Editor app than the Runestone framework, which this repository contains.
