### ISSUE TITLE
Get the NSString of the internal TextInputView

### ISSUE THREAD

**Issue by 12345CPZ** [simonbs/Runestone#222]
Hi, @simonbs . There is some performance loss in converting NSString to String. Do you have any plans to provide NSString in TextView?

**Comment by simonbs** [comment]
@12345CPZ I have no concrete plans to expose the internal NSString. However, if there's a significant performance loss in the conversion then it may make sense to expose it.

Can you provide some data that shows the performance loss? This could be screenshots or exports from the Time Profiler.

**Comment by simonbs** [comment]
Closing this.
