### ISSUE TITLE
How to undo & redo

### ISSUE THREAD

**Issue by msaitow** [simonbs/Runestone#224]
Hi guys,

I’m quite new to the Runestone text editor. So my question may sound stupid but anyways ket me ask it: How can I undo and redo the last changes? As far as I took a look at the documentations, I could not find anything about them.

Sincerely,
MS

**Comment by simonbs** [comment]
@msaitow You can get the [UndoManager](https://developer.apple.com/documentation/foundation/undomanager) that belongs to the text view and call `undo()` and `redo()` on that. Here's an example:

```swift
textView.undoManager?.undo()
```

**Comment by simonbs** [comment]
Closing this as resolved. Don't hesitate to reopen the issue if that is not the case.

**Comment by msaitow** [comment]
Thanks you for answering! But still I'm wondering how to use that UndoManager from the App. I'm talking about the Runestone App but not the framework which the App is based upon.
