### ISSUE TITLE
Screen Time restriction bypass

### ISSUE THREAD

**Issue by Aerbil** [simonbs/Runestone#241]
### Is your feature request related to a problem?

In-app Webview makes it possible to pass Screen Time restrictions on iOS, and many kids know it. Even when Safari is disabled, in-app browser will continue to work.

### What solution would you like?

Help button can directly open the default browser instead of Webview.

**Comment by simonbs** [comment]
This issue seems related to the Runestone app rather than the Runestone framework. This PR is concerned with the latter.
