### ISSUE TITLE
Caret Position

### ISSUE THREAD

**Issue by just-eric-99** [simonbs/Runestone#247]
Hello, 
I am pretty new to swift and i would like to ask if there is any API to indicate my current caret position in the editor? 
![Screenshot 2022-12-05 at 6 50 13 PM](https://user-images.githubusercontent.com/64390777/205619445-75bccb55-b836-46e4-b084-3c5c8edf8eb2.png)
In this example, how can I get the line number "4"?

Thanks in advance.

**Comment by simonbs** [comment]
Hi,

You can use `textLocation(at:)` on an instance of TextView to get the line and column number of a location in the document. Pass the location of the currently selected range to get the line and column number of the caret. [Here's the documentation for the API.](https://docs.runestone.app/documentation/runestone/textview/textlocation(at:))

The following code snippet shows how the API is used.

```swift
if let textLocation = textView.textLocation(at: textView.selectedRange.location) {
    print("Line = \(textLocation.lineNumber + 1), column = \(textLocation.column + 1)")
}
```

Note that the line and column numbers in instances of TextLocation, which `textLocation(at:)` returns, are zero-based, hence we add one to the line and column numbers.

I'm closing this issue as I believe the above answers your question but don't hesitate to re-open the issue if you need more information.

**Comment by just-eric-99** [comment]
I managed to retrieve the caret position as i wanted. Thank you very much.
