### ISSUE TITLE
Alternative to private API in sendSelectionChangedToTextSelectionView()

### ISSUE THREAD

**Issue by blach** [simonbs/Runestone#255]
Hi Simon,

I just wanted to let you know about an alternative to your private API call in sendSelectionChangedToTextSelectionView.

https://github.com/simonbs/Runestone/blob/665ef7f6cef2a74d5e2e0ebda7d293e75b5bd9fa/Sources/Runestone/TextView/Core/TextInputView.swift#L1347 

If you call inputDelegate.selectionDidChange with nil instead of self, only the text selection is updated. The text input system ignores this call.

Here is my Objective-C method for that:

```objc
- (void)updateTextSelectionViewWithoutNotifyingInputDelegate {
	// If we use UITextInteraction, the inputDelegate actually has the class UITextInteractionInputDelegate instead
	// of UITextInputDelegate. Calling -selectionDidChange: with a nil argument instead of self does not call
	// -[UIKeyboardImpl selectionDidChange:] but instead only calls -[UITextSelectionView selectionDidChange:].
	// This is exactly what we want: update the selection, but do not interfere with things like auto correction or
	// assembling Korean characters.
	[_inputDelegate selectionDidChange:nil];
}
```

I found this out by looking at UIKitCore with Hopper. Here is the pseudo-code of this method:

<img width="348" alt="hopper-pseudo-code-selectiondidchange" src="https://user-images.githubusercontent.com/1008289/212140066-5768af76-d381-431e-a5c8-4dbd0743b9ad.png">

**Comment by simonbs** [comment]
Hi Alexander,

Thanks for opening this issue and making me aware of the improvement. I've implemented the change in #257.
