### ISSUE TITLE
MacBook version

### ISSUE THREAD

**Issue by drmrbrewer** [simonbs/Runestone#274]
### Is your feature request related to a problem?

The problem is that the Runestone app appears to be available on [iPhone/iPad](https://apps.apple.com/us/app/runestone-editor/id1548193893).

### What solution would you like?

I would love it to be available on MacBook as well, with synchronisation between all devices via iCloud.

### What alternatives have you considered?

Other code editors like Textastic.

**Comment by simonbs** [comment]
This issue seems related to the Runestone Text Editor app rather than the open-source Runestone framework, which this repository contains. I'll take note of your feature request and close this issue.
