### ISSUE TITLE
The editor will not respond in some cases

### ISSUE THREAD

**Issue by 12345CPZ** [simonbs/Runestone#279]
### What happened?

Thank you for your contribution to the iOS community! 

I am trying to add tab functions to the editor, so that I can switch different tabs in a browser-like way, and each tab displays a different `TextView.` My approach is to switch different tabs in a `UIView` by adding or removing `TextView` sub-views. This seems to work well, but in some cases, after switching tabs, the editor will request the layout of the entire text. If the text is long (more than 10000 lines), the memory consumption may reach 1GB. What is the best way to implement a multi-tab editor? Under what circumstances will the editor rearrange all content?

### What are the steps to reproduce?

Add TextView as a subview to a UIView, and then remove the subview. Then add another TextView as the child view of this UIView. In the case of a large number of texts, the editor may not respond and layout the whole text after repeated experiments.

### What is the expected behavior?

The editor works well and will not layout the whole article again.

**Comment by simonbs** [comment]
@12345CPZ Can you provide a sample project to reproduce this issue?

**Comment by simonbs** [comment]
In my testing I have not found Runestone to layout the entire text at once. Without a sample project to reproduce this, I cannot get any further and will close this issue.
