### ISSUE TITLE
Formatting buttons

### ISSUE THREAD

**Issue by sybercorp** [simonbs/Runestone#280]
### Is your feature request related to a problem?

No

### What solution would you like?

Please add buttons to quickly format text without having to already know which characters do what, and without having to long-press buttons to find or which one the symbol you’re looking for is in.

For example, please add a **B** and a _I_ button, and also let them support blocks of text.

### What alternatives have you considered?

None

**Comment by simonbs** [comment]
This issue seems related to the Runestone Text Editor app. However, this repository is concerned with the Runestone framework for building performance text editors and therefore I will close the issue.

I have taken note of your feature request and may look into in a future update.
