### ISSUE TITLE
Using Hotkeys

### ISSUE THREAD

**Issue by xcojonny** [simonbs/Runestone#281]
### Is your feature request related to a problem?

Hej, 

Thanks for the awesome app!!

Is there a way to configure hotkeys? Like commenting lines etc? 
Haven‘t found it so far except for moving lines, which is great.

Best regards.

### What solution would you like?

Configure Hotkeys For Commenting.

### What alternatives have you considered?

None

**Comment by simonbs** [comment]
It is not currently possible to configure custom hotkeys in the Runestone app.

This comment seems related to the Runestone app rather than the open-source framework which this repository contains. Therefore I will close the comment.
