### ISSUE TITLE
Kotlin language support

### ISSUE THREAD

**Issue by iplusplus42** [simonbs/Runestone#300]
### Is your feature request related to a problem?

No related problem.

### What solution would you like?

I would like syntax highlighting for Kotlin. Tree-sitter already supports Kotlin as a parser, which I presume would make implementation easier.

### What alternatives have you considered?

Working Copy does have Kotlin syntax highlighting, but Runestone's editor is way more configurable.

**Comment by simonbs** [comment]
The Runestone framework is language agnostic.

I have a suspicion that this issue is related to the Runestone Text Editor app rather than the Runestone open-source framework. I will make a note to look into adding Kotlin syntax highlighting to the Runestone app in the future and close this issue.
