### ISSUE TITLE
Include more developer fonts

### ISSUE THREAD

**Issue by mbirth** [simonbs/Runestone#310]
### Is your feature request related to a problem?

I'd like to see a few more developer fonts in Runestone.

### What solution would you like?

Please add fonts like:

* [Fira Code](https://github.com/tonsky/FiraCode)
* [Fira Code 2 iScript](https://github.com/willstocks/FiraCode2iScript)
* [Victor Mono](https://rubjo.github.io/victor-mono/)

### What alternatives have you considered?

I've installed those fonts using [iFont](https://apps.apple.com/us/app/ifont-find-install-any-font/id1173222289) but they don't show up in the font picker nor the system font picker (iOS 17 Beta). (Tried profile method and the new iOS 13 method.)

**Comment by simonbs** [comment]
This issue seems specific to the Runestone Text Editor application whereas this repository is concerned with the Runestone framework. Therefore I'll close the issue.
