### ISSUE TITLE
Does this work with MacOS ?

### ISSUE THREAD

**Issue by pkasson** [simonbs/Runestone#311]
### What happened?

Does this work with MacOS ?

### What are the steps to reproduce?

Does this work with MacOS ?

### What is the expected behavior?

Does this work with MacOS ?

**Comment by simonbs** [comment]
I'm working on a version for macOS. Both the [mac](https://github.com/simonbs/Runestone/tree/mac) and [refactor](https://github.com/simonbs/Runestone/tree/refactor) somewhat work on macOS but none of the implementations are ready for production.

**Comment by aehlke** [comment]
is there an update on mac support? thank you

**Comment by github-ph-52obr** [comment]
Eager to get this on macOS!

**Comment by kleerkoat** [comment]
take my money
