### ISSUE TITLE
Xcode 15.0(iOS 17) - cursor is not visible when becoming first responder

### ISSUE THREAD

**Issue by tiandt** [simonbs/Runestone#313]
### What happened?

Cursor showing at the second click. Xcode 14.3.1 works fine.

https://github.com/simonbs/Runestone/assets/24294497/ae844898-86f2-4683-827a-3fb99f7a901b

### What are the steps to reproduce?

Run with Xcode 15, iOS 17.

### What is the expected behavior?

Show cursor immediately.

**Comment by simonbs** [comment]
This is a regression on iOS 17 that’s on my radar. Really, this is up to Apple to fix but I’m starting to think I can’t rely on that.

I have a few potential workarounds that I’m examining. Unfortunately, my time is quite limited the next couple of weeks but I will get back to it after then.

**Comment by hectortosa** [comment]
I also found that when the cursor disappears, also does the “toolbar”, in my case when back from the docs

https://github.com/simonbs/Runestone/assets/3109264/0d0c8309-fff0-452e-b3e2-6b299c9eb07f

**Comment by simonbs** [comment]
This is fixed in #314 and #317.
