### ISSUE TITLE
Internal browser

### ISSUE THREAD

**Issue by Calorion** [simonbs/Runestone#319]
### Is your feature request related to a problem?

I can't preview HTML/CSS/JavaScript.

### What solution would you like?

A critical lack in Runestone is the lack of an interval browser for viewing HTML/JavaScript live. 

Alternately, the ability to open files in Safari would work fine, but I don't know if that's possible.

### What alternatives have you considered?

Using Runestone to edit, then using the Files app too open the resulting file in Koder. This works, but is very cumbersome.

**Comment by simonbs** [comment]
This issue seems related to the Runestone app rather than the open-source Runestone framework which this repository contains. I'll therefore take note of the feature request and close the issue.
