### ISSUE TITLE
Word wrap?

### ISSUE THREAD

**Issue by jlippold** [simonbs/Runestone#32]
Is line/word wrapping a configurable option with premium?

Thanks

**Comment by simonbs** [comment]
> Is line/word wrapping a configurable option with premium?
> 
> Thanks

You can disable line wrapping with Premium. I'm closing the issue since it seems to be related to the Runestone app, where this issue tracker is concerned with the Runestone framework.

**Comment by jlippold** [comment]
ohh my bad simon, I didnt know how else to contact you. Nice job on the app, btw. I dig it
