### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by good1uck** [simonbs/Runestone#322]
### What area of the framework would you like to have improved the documentation for?

Sorry i am new , I have sucessfully build this project, but nothing shows up. 
Should there be a simulator jump up and start the App or else? Or is there a button in Xcode that can run the app after building?

### Why is the current documentation for this area not sufficient?

It's not clear that how should run this app..

**Comment by RNCST-CEO** [comment]
`

**Comment by simonbs** [comment]
Please run the example project that resides in the Example folder.
