### ISSUE TITLE
Support for the Nix language

### ISSUE THREAD

**Issue by SpyHoodle** [simonbs/Runestone#332]
### Is your feature request related to a problem?

There is no support for the nix language in Runestone.

### What solution would you like?

This to be added so that I can have syntax highlighting of nix files.

### What alternatives have you considered?

n/a

**Comment by simonbs** [comment]
The open-source Runestone framework does not know if any languages specifically. This issue seems to be related to the Runestone Text Editor app, which does not reside in this repository, and therefore I will close this issue.
