### ISSUE TITLE
Caret position not updating when setting selectedRange

### ISSUE THREAD

**Issue by jbromberg** [simonbs/Runestone#335]
### What happened?

When manually setting `selectedRange` after inserting new text the visual position of the caret is wrong. Once I start typing, the text goes to the position specified by `selectedRange` and the caret updates. It seems like there may be caret position updating logic in the `replace()` function that is conflicting with the `selectedRange` setter.

### What are the steps to reproduce?

```swift
replace(NSMakeRange(0, 0), withText: "Hello, world!")
selectedRange = NSMakeRange(5, 0)
```

### What is the expected behavior?

Caret position is display based on the `selectedRange` property.

**Comment by simonbs** [comment]
Thanks for opening the issue. I believe it's addressed in #364.
