### ISSUE TITLE
Show character code point on selected code or current character at cursor

### ISSUE THREAD

**Issue by scriptam** [simonbs/Runestone#336]
### Is your feature request related to a problem?

No

### What solution would you like?

I’d like to see the code point for the character I highlighted (or equivalent code unit in encoding code space) 

This is especially helpful to surface invisible characters and distinguish them from each other. Alternative use case is to distinguish unicode characters that look like Latin counterparts. Another use is to differentiate hyphens, quotes and other visibly similar but technically different characters. Able to see each character’s underlying value help in several ways.

Example:

Once a character is selected, enhance the number of selected character count “(…)” with an additional value displayed, namely, its code point: like value 0x20 for space character

Ideally:

Make the display format of code point user definable
in settings (Hexadecimal or its Int equivalent Unicode value, etc)

### What alternatives have you considered?

Using a hex editor and paste the value back. Having this feature negates the need for other editors.

**Comment by simonbs** [comment]
This feature request seems to belong in an app implementing the Runestone framework rather than the framework itself.

Closing the issue as I do not think the feature belongs in this framework at this point.
