### ISSUE TITLE
Creating a note in Google Drive directly fails

### ISSUE THREAD

**Issue by JMulder99** [simonbs/Runestone#368]
I have my Google Drive connected to IOS Files. If I try to create a new note directly in Google Drive, the following message appears: "Failed opening document. Couldn't communicate with helper application."

A screenshot shows the error message. 
![image](https://github.com/simonbs/Runestone/assets/52777149/7efe72f5-a15b-458b-87e2-269f5b1d015f)

**Comment by simonbs** [comment]
I believe this is an issue with Google Drive’s implementation of iOS’ File Providers rather than Runestone.

Because this issue is related to the Runestone Text Editor app rather than the Runestone open-source framework that this repository contains, I will close the issue.
