### ISSUE TITLE
Get content size before it actually renders

### ISSUE THREAD

**Issue by 07akioni** [simonbs/Runestone#370]
### Is your feature request related to a problem?

I'm using runestone as a readonly code block and I want to display all its content. However current `contentSize` is not suitable for getting real content height.

### What solution would you like?

Add a property to enable getting real content height.

### What alternatives have you considered?

Nope.

**Comment by simonbs** [comment]
This has come up before and was briefly discussed in https://github.com/simonbs/Runestone/issues/355. Have you looked into whether the [StringSyntaxHighlighter](https://docs.runestone.app/documentation/runestone/stringsyntaxhighlighter ) could be the way to go for your use case?

**Comment by 07akioni** [comment]
Thanks, I think it may satisfies my use case. Sorry for didn't notice that.
