### ISSUE TITLE
Support .qmd files

### ISSUE THREAD

**Issue by mauriciomm7** [simonbs/Runestone#378]
### Is your feature request related to a problem?

Yes, the problem is that even though `.qmd` files open as plain text without problem, it does not have a proper aesthetics that differentiates code blocks from plain text and such. 

### What solution would you like?

I think the solution would be to use the markdown settings in general and add a code snippetting feature that detects the code chunks in python, R or julia every time backticks plus language are used as preambles ```{R}```. 

In theory Runstone already has all the necessary code and its just a matter of blending the styles together.

### What alternatives have you considered?

Yes, I already tried opening `.qmd` files with markdown which make sense for everything except the code chunks which I referred to above.  

### Any additional context?

VSCode already has the formatting settings for qmd files too (see picture attached) so it would look something like this, without the run this cell text. 
![IMG_0084](https://github.com/simonbs/Runestone/assets/62481563/d3d78082-7817-480c-aeae-eff900947518)

**Comment by simonbs** [comment]
Closing this as the Runestone framework does not deal with any languages specifically, so this issue is likely about the Runestone Text Editor app, which the issue tracker in this repository isn't intended for.
