### ISSUE TITLE
Checking for user changes does not work

### ISSUE THREAD

**Issue by hooczech** [simonbs/Runestone#381]
### What happened?

Checking whether user did any changes to the text does not work, onChange function does not fire

### What are the steps to reproduce?

We want to check if there is any text addition to the editor by user. We use SwiftUI.

We have simple wrapper as: 

```
import Runestone
import SwiftUI


struct RunestoneTextViewWrapper: UIViewRepresentable {
    @Binding var textView: TextView

    func makeUIView(context: Context) -> TextView {
        textView
    }

    func updateUIView(_ uiView: TextView, context: Context) {
        if uiView.text != textView.text {
            uiView.text = textView.text
        }
    }
}
```

We have follwing way to try to check for user input/changes, however this is never called when user interacts with the text

```
ZStack(alignment: .topTrailing) {
    ScrollView {
        RunestoneTextViewWrapper(textView: $textView)
            .onAppear {
             //...
            }
            .onChange(of: textView.text) { oldValue, newValue in
                self.hasChanges = true
                self.updateThingsToDoCount(text: newValue)
            }
    }
}
```

### What is the expected behavior?

fire the onChange function

**Comment by vvisionnn** [comment]
> just have quick look and didn't try on my computer

so you are passing the `TextView` as a binding which is a reference type
that is not the recommend way to monitoring the change
possible a solution:
try make the `text string` as a binding not the `TextView`, then you can monitor the change of text instead of `textView.text`

**Comment by simonbs** [comment]
You should use the TextViewDelegate to observe changes in the text view.

Runestone has no SwiftUI wrapper, so this does not appear to be an issue in Runestone.
