### ISSUE TITLE
Flicker when using themes and switching between multiple windows on iPad os

### ISSUE THREAD

**Issue by felixbinder** [simonbs/Runestone#388]
### What happened?

This is on 1.5.2 and iPad OS 18.0. 

When using a theme and multiple window, switching between windows leads to the theme briefly resetting to the default (?), leading to an annoying flash. 

Uploading IMG_4642.mov…

### What are the steps to reproduce?

Set theme
Open multiple windows in stage manager or via popover
switch focus

### What is the expected behavior?

no flicker.

**Comment by simonbs** [comment]
This issue seems to be about the Runestone Text Editor app rather than the open-source Runestone framework, which this repository contains. Therefore, I'll close the issue.

**Comment by felixbinder** [comment]
Sorry about that—for clarity, I got here via the Github button on https://runestone.app
