### ISSUE TITLE
Highlight more languages

### ISSUE THREAD

**Issue by MalteKiefer** [simonbs/Runestone#389]
### Is your feature request related to a problem?

No.
I just want to ask if you can support more language highlighting like:

- Powershell
- XML

### What solution would you like?

No

### What alternatives have you considered?

No

**Comment by simonbs** [comment]
Closing this as the Runestone framework does not deal with any languages specifically, so this issue is likely about the Runestone Text Editor app, which the issue tracker in this repository isn't intended for.
