### ISSUE TITLE
Double digit line numbers truncate with a font size greater or equal to 20

### ISSUE THREAD

**Issue by ptrkstr** [simonbs/Runestone#43]
**Describe the bug**
Double digit line numbers truncate with a font size greater or equal to 20

**To Reproduce**
1. Open the Example project.
2. Navigate to `OneDarkTheme.swift`.
3. Set the font to a size of 20 or greater.
4. Run the project
5. Set theme to `One Dark`
6. Enter enough new lines to see 10 rows

**Expected behavior**
- Line numbers don't truncate.
- Line number gutter increases in width to accommodate the double digits at the larger font size.

**Screenshots**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/11362913/167944513-f3b59b3f-4369-40a5-9392-a8c83092cb11.png">

**Comment by simonbs** [comment]
Thanks for reporting this and providing detailed steps to reproduce the issue. It's fixed by #44.

**Comment by ptrkstr** [comment]
Thanks for fixing that so quickly @simonbs 🙏
