### ISSUE TITLE
Option to disable font ligatures

### ISSUE THREAD

**Issue by amadejpapez** [simonbs/Runestone#50]
**Is your feature request related to a problem? Please describe.**
"The problem" is that Runestone uses font ligatures, so it joins characters like `== != <= => <==>` together.

Example: (with JetBrains Mono)

![image](https://user-images.githubusercontent.com/63184600/168253215-02d49086-c59c-4184-9342-e43348298a8b.jpeg)

**Describe the solution you'd like**
An option to disable font ligatures.

**Describe alternatives you've considered**
/

**Comment by simonbs** [comment]
I'd like to support this in the Runestone framework, and I recently tried setting NSAttributedString.Key.ligature to 0 when creating the underlying NSAttributedString in Runestone [as suggested in the documentation](https://developer.apple.com/documentation/foundation/nsattributedstring/key/1524592-ligature) but it didn't disable the ligatures.

I haven't figured out any other way to disable the ligatures so I'm afraid I've reached a dead end with this issue for now.

**Comment by amadejpapez** [comment]
Thank you for looking into this!

I am not sure about other fonts but JetBrains Mono does offer special TTF files that have no ligatures (named NL). If adding new fonts is an option.

**Comment by simonbs** [comment]
> If adding new fonts is an option.

Adding new fonts to the Runestone app may be an option but this issue tracker is concerned with the open-source framework that the Runestone app is built on. The framework does not include any fonts and I don't want to start bundling fonts with the framework.

However, if you're mainly concerned with the Runestone app (and not the framework), you can use an app such as [Fontcase](https://apps.apple.com/us/app/fontcase-manage-your-type/id1205074470) to install your preferred font and it should become available in Runestone's font picker.

**Comment by amadejpapez** [comment]
> you can use an app such as Fontcase to install your preferred font and it should become available in Runestone's font picker.

Nice, I had no idea about this. So regarding the app, this worked and I was able to select JetBrains Mono without ligatures. Thank you :)

**Comment by simonbs** [comment]
> So regarding the app, this worked and I was able to select JetBrains Mono without ligatures. Thank you :)

Glad to hear you got it working.

Since this issue was mostly related to the Runestone app, I'll close it.
