### ISSUE TITLE
Automatic theme switches when toggling light/dark mode

### ISSUE THREAD

**Issue by nighthawk** [simonbs/Runestone#69]
**Is your feature request related to a problem? Please describe.**
The theme system allows specifying a single theme, which would be optimised for either light or dark mode. There doesn't yet seem a way to either set a single theme that supports both light and dark mode, or specify a theme per interface style.

**Describe the solution you'd like**
This could be addressed by providing multiple themes, one per `UIUserInterfaceStyle`, or by providing support for themes that support multiple interface styles.

**Describe alternatives you've considered**
- I've tried adjusting the Color Set in my asset catalog to provide alternative colours for light and dark mode. This seems to work for a subset of colours, but notable not for the background colours. I'm also not sure if that's fully compatible with the internals of Runestone.
- Detect this on my view controllers, and then set the new theme.

**Additional context**
I'm happy to provide a PR for this, but I'm not sure if this is desired and, if so, which approach would be the best fit for this framework.

**Comment by nighthawk** [comment]
Ah, right, I had grabbed one of the example themes as the starting point for my theme and missed the difference between Runestone's Theme protocol and the EditorTheme in sample project. I wrongly thought the `backgroundColor` to be part of the Theme protocol, when it's not. Is there a reason for that? In my head they are closely tied together as, say, the choice of a text colour very much depends on the background colour.

I agree that having a single `theme` property on TextView makes more sense than having a `lightTheme` and `darkTheme`, and then using dynamic colours in there. That works very well already -- as long as the same is done on the current `*Color` properties on TextView. I merged Tomorrow and TomorrowNight into colour set and that works out of the box with Runestone as is:

<img width="921" alt="Screen Shot 2022-05-28 at 16 07 32" src="https://user-images.githubusercontent.com/22646/170812607-37e8ebee-1b93-401b-b796-a24b8f0e7196.png">

So my feature request is somewhat void as this works well like that.

My recommendation would be that all the colour properties are encapsulated in *some* theme protocol. It could be just moving the EditorTheme (without the interface mode) into the Runestone project and moving TextView properties such as `backgroundColor`, or `insertionPointColor` in there. EditorTheme could extend Theme as it does in the sample project, or could be separate.

**Comment by simonbs** [comment]
> Ah, right, I had grabbed one of the example themes as the starting point for my theme and missed the difference between Runestone's Theme protocol and the EditorTheme in sample project. I wrongly thought the `backgroundColor` to be part of the Theme protocol, when it's not. Is there a reason for that? In my head they are closely tied together as, say, the choice of a text colour very much depends on the background colour.

I agree that they're quite closely tied together. The main reason for not having background color being part of the Theme protocol is that it isn't strictly necessary and I can't stop people from setting the background color of the TextView instance manually through `textView.backgroundColor = .systemRed`, as is required now. That raises the questions:

- What's the difference between setting the background color directly and through the team?
- And which one has precedence?

To avoid dealing with those questions I left the background color out of the Theme protocol.

> I agree that having a single `theme` property on TextView makes more sense than having a `lightTheme` and `darkTheme`, and then using dynamic colours in there. That works very well already -- as long as the same is done on the current `*Color` properties on TextView.

I also quite like that we only have to set a single theme. Let's stick with that then.

> I merged Tomorrow and TomorrowNight into colour set and that works out of the box with Runestone as is:

Glad to hear it works.

> So my feature request is somewhat void as this works well like that.

I'd love to hear your thoughts on my concerns with including the background color in the Theme protocol. Depending on what you get back with before considering this feature request void and closing the issue.

**Comment by nighthawk** [comment]
> I agree that they're quite closely tied together. The main reason for not having background color being part of the Theme protocol is that it isn't strictly necessary and I can't stop people from setting the background color of the TextView instance manually through `textView.backgroundColor = .systemRed`, as is required now. That raises the questions:
> 
> * What's the difference between setting the background color directly and through the team?
> * And which one has precedence?
> 
> To avoid dealing with those questions I left the background color out of the Theme protocol.

Right, that makes sense that this leads to some ambiguity if there are two ways to define the background colour.

Though conceptually it seems _nice_ if you can set and update all the colours through a single Theme protocol. Say, `RunestoneSwiftUI` could then also take a `Binding<Theme>`, you can have a picker to choose the theme, and it handles theme switches through that one binding, rather than also needing to separately update the background colour.

How about having `var backgroundColor: UIColor?` in the Theme protocol with a default implementation of `nil`? That way it maintains backwards compatibility and it's a hint that if it's provided it would take precedence over `textView.backgroundColor`.

**Comment by simonbs** [comment]
> How about having `var backgroundColor: UIColor?` in the Theme protocol with a default implementation of `nil`? That way it maintains backwards compatibility and it's a hint that if it's provided it would take precedence over `textView.backgroundColor`.

That could work but I think there would still be some ambiguity that's difficult to understand. If you apply a theme with a non-nil background color and then set the background color directly on the TextView, then the latter wouldn't have any effect if the theme takes precedence. It isn't too bad but it's an ambiguity that I'd prefer to avoid.

Since the core of this issue seems to be addressed, I'll close the issue. If there's still a desire to introduce a background color on the Theme, either now or in the future, I think we should open a new issue 😊
